.PHONY: clean All

All:
	@echo "----------Building project:[ sequence1 - Debug ]----------"
	@cd "sequence1" && "$(MAKE)" -f  "sequence1.mk"
clean:
	@echo "----------Cleaning project:[ sequence1 - Debug ]----------"
	@cd "sequence1" && "$(MAKE)" -f  "sequence1.mk" clean
