.PHONY: clean All

All:
	@echo "----------Building project:[ perfectnum - Debug ]----------"
	@"$(MAKE)" -f  "perfectnum.mk"
clean:
	@echo "----------Cleaning project:[ perfectnum - Debug ]----------"
	@"$(MAKE)" -f  "perfectnum.mk" clean
