.PHONY: clean All

All:
	@echo "----------Building project:[ Assignment4a - Debug ]----------"
	@cd "Assignment4a" && "$(MAKE)" -f  "Assignment4a.mk"
clean:
	@echo "----------Cleaning project:[ Assignment4a - Debug ]----------"
	@cd "Assignment4a" && "$(MAKE)" -f  "Assignment4a.mk" clean
