.PHONY: clean All

All:
	@echo "----------Building project:[ quadraticexpression - Debug ]----------"
	@cd "quadraticexpression" && "$(MAKE)" -f  "quadraticexpression.mk"
clean:
	@echo "----------Cleaning project:[ quadraticexpression - Debug ]----------"
	@cd "quadraticexpression" && "$(MAKE)" -f  "quadraticexpression.mk" clean
