.PHONY: clean All

All:
	@echo "----------Building project:[ bmi - Debug ]----------"
	@"$(MAKE)" -f  "bmi.mk"
clean:
	@echo "----------Cleaning project:[ bmi - Debug ]----------"
	@"$(MAKE)" -f  "bmi.mk" clean
